# Created by JDXE
# Cloned from Gruvbox Rainbow
# Heavily Inspired by Gruvbox Rainbow,Pastel Powerline, and Tokyo Night.

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](colour_ff4e4e)\
$os\
$username\
[](bg:colour_ff7272 fg:colour_ff4e4e)\
$directory\
[](fg:colour_ff7272 bg:colour_ff8d8d)\
$git_branch\
$git_status\
[](fg:colour_ff8d8d bg:colour_ffadad)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:colour_ffadad bg:colour_ffd2d2)\
$docker_context\
$conda\
[](fg:colour_ffd2d2 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$character"""

palette = 'apple'

[palettes.apple]
colour_foreground = '#ffd2d2'
color_bg1 = '#3c3836'
colour_ffd2d2 = '#ffd2d2'
colour_ffadad = '#ffadad'
colour_ff8d8d = '#ff8d8d'
colour_arrow = '#ff4e4e'
colour_ff4e4e = '#ff4e4e'
colour_FFA500 = '#FFA500'
color_red = '#cc241d'
colour_ff7272 = '#ff7272'

[os]
disabled = false
style = "bg:colour_ff4e4e fg:colour_foreground"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:colour_ff4e4e fg:colour_foreground"
style_root = "bg:colour_ff4e4e fg:colour_foreground"
format = '[ $user ]($style)'

[directory]
style = "fg:colour_foreground bg:colour_ff7272"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:colour_ff8d8d"
format = '[[ $symbol $branch ](fg:colour_foreground bg:colour_ff8d8d)]($style)'

[git_status]
style = "bg:colour_ff8d8d"
format = '[[($all_status$ahead_behind )](fg:colour_foreground bg:colour_ff8d8d)]($style)'

[nodejs]
symbol = ""
style = "bg:colour_ffadad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_ffadad)]($style)'

[c]
symbol = " "
style = "bg:colour_ffadad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_ffadad)]($style)'

[rust]
symbol = ""
style = "bg:colour_ffadad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_ffadad)]($style)'

[golang]
symbol = ""
style = "bg:colour_ffadad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_ffadad)]($style)'

[php]
symbol = ""
style = "bg:colour_ffadad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_ffadad)]($style)'

[java]
symbol = " "
style = "bg:colour_ffadad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_ffadad)]($style)'

[kotlin]
symbol = ""
style = "bg:colour_ffadad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_ffadad)]($style)'

[haskell]
symbol = ""
style = "bg:colour_ffadad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_ffadad)]($style)'

[python]
symbol = ""
style = "bg:colour_ffadad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_ffadad)]($style)'

[docker_context]
symbol = ""
style = "bg:colour_ffd2d2"
format = '[[ $symbol( $context) ](fg:#83a598 bg:colour_ffd2d2)]($style)'

[conda]
style = "bg:colour_ffd2d2"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:colour_ffd2d2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:colour_foreground bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ 〉](bold fg:colour_arrow)'
error_symbol = '[ 〉](bold fg:color_red)'
vimcmd_symbol = '[〈](bold fg:colour_arrow)'
vimcmd_replace_one_symbol = '[〈](bold fg:colour_FFA500)'
vimcmd_replace_symbol = '[〈](bold fg:colour_FFA500)'
vimcmd_visual_symbol = '[〈](bold fg:colour_ff7272)'