# Created by JDXE
# Cloned from Gruvbox Rainbow
# Heavily Inspired by Gruvbox Rainbow,Pastel Powerline, and Tokyo Night.

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](colour_66ff4b)\
$os\
$username\
[](bg:colour_8aff6f fg:colour_66ff4b)\
$directory\
[](fg:colour_8aff6f bg:colour_9aff8d)\
$git_branch\
$git_status\
[](fg:colour_9aff8d bg:colour_baffad)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:colour_baffad bg:colour_d9ffd2)\
$docker_context\
$conda\
[](fg:colour_d9ffd2 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$character"""

palette = 'grass'

[palettes.grass]
colour_foreground = '#d9ffd2'
color_bg1 = '#3c3836'
colour_d9ffd2 = '#d9ffd2'
colour_baffad = '#baffad'
colour_9aff8d = '#9aff8d'
colour_arrow = '#66ff4b'
colour_66ff4b = '#66ff4b'
colour_228B22 = '#228B22'
color_red = '#cc241d'
colour_8aff6f = '#8aff6f'

[os]
disabled = false
style = "bg:colour_66ff4b fg:colour_foreground"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:colour_66ff4b fg:colour_foreground"
style_root = "bg:colour_66ff4b fg:colour_foreground"
format = '[ $user ]($style)'

[directory]
style = "fg:colour_foreground bg:colour_8aff6f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:colour_9aff8d"
format = '[[ $symbol $branch ](fg:colour_foreground bg:colour_9aff8d)]($style)'

[git_status]
style = "bg:colour_9aff8d"
format = '[[($all_status$ahead_behind )](fg:colour_foreground bg:colour_9aff8d)]($style)'

[nodejs]
symbol = ""
style = "bg:colour_baffad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_baffad)]($style)'

[c]
symbol = " "
style = "bg:colour_baffad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_baffad)]($style)'

[rust]
symbol = ""
style = "bg:colour_baffad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_baffad)]($style)'

[golang]
symbol = ""
style = "bg:colour_baffad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_baffad)]($style)'

[php]
symbol = ""
style = "bg:colour_baffad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_baffad)]($style)'

[java]
symbol = " "
style = "bg:colour_baffad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_baffad)]($style)'

[kotlin]
symbol = ""
style = "bg:colour_baffad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_baffad)]($style)'

[haskell]
symbol = ""
style = "bg:colour_baffad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_baffad)]($style)'

[python]
symbol = ""
style = "bg:colour_baffad"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_baffad)]($style)'

[docker_context]
symbol = ""
style = "bg:colour_d9ffd2"
format = '[[ $symbol( $context) ](fg:#83a598 bg:colour_d9ffd2)]($style)'

[conda]
style = "bg:colour_d9ffd2"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:colour_d9ffd2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:colour_foreground bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ 〉](bold fg:colour_arrow)'
error_symbol = '[ 〉](bold fg:color_red)'
vimcmd_symbol = '[〈](bold fg:colour_arrow)'
vimcmd_replace_one_symbol = '[〈](bold fg:colour_228B22)'
vimcmd_replace_symbol = '[〈](bold fg:colour_228B22)'
vimcmd_visual_symbol = '[〈](bold fg:colour_8aff6f)'