# Created by JDXE
# Cloned from Gruvbox Rainbow
# Heavily Inspired by Gruvbox Rainbow,Pastel Powerline, and Tokyo Night.

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](colour_c9ae74)\
$os\
$username\
[](bg:colour_d4be90 fg:colour_c9ae74)\
$directory\
[](fg:colour_d4be90 bg:colour_dfceac)\
$git_branch\
$git_status\
[](fg:colour_dfceac bg:colour_e9dfc7)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:colour_e9dfc7 bg:colour_f4efe3)\
$docker_context\
$conda\
[](fg:colour_f4efe3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$character"""

palette = 'sand'

[palettes.sand]
colour_foreground = '#f4efe3'
color_bg1 = '#3c3836'
colour_f4efe3 = '#f4efe3'
colour_e9dfc7 = '#e9dfc7'
colour_dfceac = '#dfceac'
colour_arrow = '#c9ae74'
colour_c9ae74 = '#c9ae74'
colour_64573a = '#64573a'
color_red = '#cc241d'
colour_d4be90 = '#d4be90'

[os]
disabled = false
style = "bg:colour_c9ae74 fg:colour_foreground"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:colour_c9ae74 fg:colour_foreground"
style_root = "bg:colour_c9ae74 fg:colour_foreground"
format = '[ $user ]($style)'

[directory]
style = "fg:colour_foreground bg:colour_d4be90"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:colour_dfceac"
format = '[[ $symbol $branch ](fg:colour_foreground bg:colour_dfceac)]($style)'

[git_status]
style = "bg:colour_dfceac"
format = '[[($all_status$ahead_behind )](fg:colour_foreground bg:colour_dfceac)]($style)'

[nodejs]
symbol = ""
style = "bg:colour_e9dfc7"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_e9dfc7)]($style)'

[c]
symbol = " "
style = "bg:colour_e9dfc7"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_e9dfc7)]($style)'

[rust]
symbol = ""
style = "bg:colour_e9dfc7"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_e9dfc7)]($style)'

[golang]
symbol = ""
style = "bg:colour_e9dfc7"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_e9dfc7)]($style)'

[php]
symbol = ""
style = "bg:colour_e9dfc7"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_e9dfc7)]($style)'

[java]
symbol = " "
style = "bg:colour_e9dfc7"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_e9dfc7)]($style)'

[kotlin]
symbol = ""
style = "bg:colour_e9dfc7"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_e9dfc7)]($style)'

[haskell]
symbol = ""
style = "bg:colour_e9dfc7"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_e9dfc7)]($style)'

[python]
symbol = ""
style = "bg:colour_e9dfc7"
format = '[[ $symbol( $version) ](fg:colour_foreground bg:colour_e9dfc7)]($style)'

[docker_context]
symbol = ""
style = "bg:colour_f4efe3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:colour_f4efe3)]($style)'

[conda]
style = "bg:colour_f4efe3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:colour_f4efe3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:colour_foreground bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[󰜐 〉](bold fg:colour_arrow)'
error_symbol = '[󰜐 〉](bold fg:color_red)'
vimcmd_symbol = '[〈](bold fg:colour_arrow)'
vimcmd_replace_one_symbol = '[〈](bold fg:colour_64573a)'
vimcmd_replace_symbol = '[〈](bold fg:colour_64573a)'
vimcmd_visual_symbol = '[〈](bold fg:colour_d4be90)'